AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Music Poetry Canvas Backend - Serverless API

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        LOG_LEVEL: INFO
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:
  # ============================================================================
  # Poetry Generation Function (Node.js + Bedrock)
  # ============================================================================
  PoetryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: poetry-function/
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          AWS_BEDROCK_REGION: !Ref AWS::Region
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: 
              - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-haiku-20240307-v1:0'
              - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-5-sonnet-20241022-v2:0'
      Events:
        PoetryGenerate:
          Type: Api
          Properties:
            Path: /api/poetry/generate
            Method: post

  # ============================================================================
  # YouTube Processing Function (Container Image with yt-dlp + librosa)
  # ============================================================================
  YouTubeFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 2048
      Timeout: 60
      Events:
        YouTubeInfo:
          Type: Api
          Properties:
            Path: /api/youtube/info
            Method: get
        YouTubeAudioWithAnalysis:
          Type: Api
          Properties:
            Path: /api/youtube/audio-with-analysis
            Method: get
    Metadata:
      DockerTag: python3.11-v1
      DockerContext: ./youtube-function
      Dockerfile: Dockerfile

  # ============================================================================
  # Thumbnail Proxy Function (Node.js)
  # ============================================================================
  # ThumbnailFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: thumbnail-function/
  #     Handler: index.handler
  #     Runtime: nodejs20.x
  #     MemorySize: 256
  #     Timeout: 10
  #     Events:
  #       ThumbnailProxy:
  #         Type: Api
  #         Properties:
  #           Path: /api/thumbnail
  #           Method: get

  # ============================================================================
  # Lambda Layers removed - using Container Image for YouTube function
  # ============================================================================

  # ============================================================================
  # Alarms removed to simplify deployment
  # Alarms commented out to simplify deployment

  # ============================================================================
  # CloudWatch Alarms - Thumbnail Function
  # ============================================================================
  
  # ThumbnailFunctionErrorAlarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmName: !Sub "${AWS::StackName}-ThumbnailFunction-Errors"
  #     AlarmDescription: "Alert when Thumbnail Function error rate exceeds 5%"
  #     MetricName: Errors
  #     Namespace: AWS/Lambda
  #     Statistic: Sum
  #     Period: 300  # 5 minutes
  #     EvaluationPeriods: 1
  #     Threshold: 5
  #     ComparisonOperator: GreaterThanThreshold
  #     Dimensions:
  #       - Name: FunctionName
  #         Value: !Ref ThumbnailFunction
  #     AlarmActions:
  #       - !Ref AlarmNotificationTopic
  #     TreatMissingData: notBreaching

  # ThumbnailFunctionDurationAlarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmName: !Sub "${AWS::StackName}-ThumbnailFunction-Duration"
  #     AlarmDescription: "Alert when Thumbnail Function duration exceeds 80% of timeout (8s)"
  #     MetricName: Duration
  #     Namespace: AWS/Lambda
  #     Statistic: Average
  #     Period: 300  # 5 minutes
  #     EvaluationPeriods: 2
  #     Threshold: 8000  # 8 seconds in milliseconds (80% of 10s timeout)
  #     ComparisonOperator: GreaterThanThreshold
  #     Dimensions:
  #       - Name: FunctionName
  #         Value: !Ref ThumbnailFunction
  #     AlarmActions:
  #       - !Ref AlarmNotificationTopic
  #     TreatMissingData: notBreaching

  # ThumbnailFunctionThrottleAlarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmName: !Sub "${AWS::StackName}-ThumbnailFunction-Throttles"
  #     AlarmDescription: "Alert when Thumbnail Function is throttled"
  #     MetricName: Throttles
  #     Namespace: AWS/Lambda
  #     Statistic: Sum
  #     Period: 300  # 5 minutes
  #     EvaluationPeriods: 1
  #     Threshold: 1
  #     ComparisonOperator: GreaterThanOrEqualToThreshold
  #     Dimensions:
  #       - Name: FunctionName
  #         Value: !Ref ThumbnailFunction
  #     AlarmActions:
  #       - !Ref AlarmNotificationTopic
  #     TreatMissingData: notBreaching

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  PoetryFunctionArn:
    Description: "Poetry Generation Lambda Function ARN"
    Value: !GetAtt PoetryFunction.Arn
  
  YouTubeFunctionArn:
    Description: "YouTube Processing Lambda Function ARN"
    Value: !GetAtt YouTubeFunction.Arn
