AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Music Poetry Canvas Backend - Serverless API (No Layers for Local Testing)

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        LOG_LEVEL: INFO
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:
  # ============================================================================
  # Poetry Generation Function (Node.js + Bedrock)
  # ============================================================================
  PoetryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: poetry-function/
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          AWS_BEDROCK_REGION: !Ref AWS::Region
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: 
              - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-haiku-20240307-v1:0'
              - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-5-sonnet-20241022-v2:0'
      Events:
        PoetryGenerate:
          Type: Api
          Properties:
            Path: /api/poetry/generate
            Method: post

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  PoetryFunctionArn:
    Description: "Poetry Generation Lambda Function ARN"
    Value: !GetAtt PoetryFunction.Arn
